// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDldOc2jNR52dpImK3eE9CYP1yetmYlIC4',
    appId: '1:393058460742:web:c687501cef5a78eb6cd647',
    messagingSenderId: '393058460742',
    projectId: 'nartaky-a6aa2',
    authDomain: 'nartaky-a6aa2.firebaseapp.com',
    storageBucket: 'nartaky-a6aa2.firebasestorage.app',
    measurementId: 'G-729L582EF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt1PBLI_OU1x0XhLV4EU1oGiU08xO8Mic',
    appId: '1:393058460742:android:8ae2354cceb9cb856cd647',
    messagingSenderId: '393058460742',
    projectId: 'nartaky-a6aa2',
    storageBucket: 'nartaky-a6aa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEwckqzG2lUYj7AFjGZ3XiKmqT__NmGHE',
    appId: '1:393058460742:ios:149eb8aaacf241a76cd647',
    messagingSenderId: '393058460742',
    projectId: 'nartaky-a6aa2',
    storageBucket: 'nartaky-a6aa2.firebasestorage.app',
    iosBundleId: 'com.example.nrtaky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEwckqzG2lUYj7AFjGZ3XiKmqT__NmGHE',
    appId: '1:393058460742:ios:149eb8aaacf241a76cd647',
    messagingSenderId: '393058460742',
    projectId: 'nartaky-a6aa2',
    storageBucket: 'nartaky-a6aa2.firebasestorage.app',
    iosBundleId: 'com.example.nrtaky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDldOc2jNR52dpImK3eE9CYP1yetmYlIC4',
    appId: '1:393058460742:web:1bdff8c8de6808f56cd647',
    messagingSenderId: '393058460742',
    projectId: 'nartaky-a6aa2',
    authDomain: 'nartaky-a6aa2.firebaseapp.com',
    storageBucket: 'nartaky-a6aa2.firebasestorage.app',
    measurementId: 'G-JMV0CNW7C2',
  );
}
